ddpg_params: {
  control_pub_name: '/racecar2/drive_parameters',
  ego_odom_name: '/racecar2/odom',
  lead_odom_name: '/racecar/odom',
  lidar_name: '/racecar2/scan',
  max_turn_angle: 34.0, 
  min_speed: 0.5, 
  max_speed: 4.0, 
  min_dist: 0.1, 
  max_dist: 3.0, 
  crash_threshold: 10,
  env: 'sim', 
  rate: 10,
  load_path: None, 
  log_path: './ddpg/',
  save_interval: 10, 
  save_path: './ddpg/',
  episode_length: 1200,
  replay_capacity: 10000,
  total_steps: 1e9,
  test_length: 600,
  num_tests: 4,
  batch_size: 100, 
  actor_learning_rate: 1e-4, 
  critic_learning_rate: 1e-3,
  weight_decay: 1e-2, 
  gamma: 0.99, 
  tau: 0.001,
  OU_sigma: 0.2,
  OU_theta: 0.15,
  test_or_train: 'train'
}