name: base
channels:
  - jdh88
  - auto
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03=py27_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py27_0
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.12=py27_0
  - anaconda=custom=py27_1
  - anaconda-client=1.7.2=py27_0
  - anaconda-navigator=1.9.6=py27_0
  - anaconda-project=0.8.2=py27_0
  - asn1crypto=0.24.0=py27_0
  - astroid=1.6.5=py27_0
  - astropy=2.0.9=py27hdd07704_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - av=6.2.0=py27ha5cc088_0
  - babel=2.6.0=py27_0
  - backcall=0.1.0=py27_0
  - backports=1.0=py27_1
  - backports.functools_lru_cache=1.5=py27_1
  - backports.os=0.1.1=py27_0
  - backports.shutil_get_terminal_size=1.0.0=py27_2
  - backports_abc=0.5=py27_0
  - beautifulsoup4=4.7.1=py27_1
  - bitarray=0.8.3=py27h14c3975_0
  - bkcharts=0.2=py27_0
  - blas=1.0=mkl
  - blaze=0.11.3=py27_0
  - bleach=3.1.0=py27_0
  - blosc=1.14.4=hdbcaa40_0
  - bokeh=1.0.4=py27_0
  - boto=2.49.0=py27_0
  - bottleneck=1.2.1=py27h035aef0_1
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2019.8.28=0
  - cairo=1.14.12=h8948797_3
  - cdecimal=2.3=py27h14c3975_3
  - certifi=2019.9.11=py27_0
  - cffi=1.12.2=py27h2e261b9_1
  - chardet=3.0.4=py27_1
  - click=7.0=py27_0
  - cloudpickle=0.8.0=py27_0
  - clyent=1.2.2=py27_1
  - colorama=0.4.1=py27_0
  - conda=4.7.12=py27_0
  - conda-build=3.17.8=py27_0
  - conda-env=2.6.0=1
  - conda-package-handling=1.3.10=py27_0
  - conda-verify=3.1.1=py27_0
  - configparser=3.7.3=py27_1
  - contextlib2=0.5.5=py27_0
  - cryptography=2.6.1=py27h1ba5d50_0
  - curl=7.63.0=hbc83047_1000
  - cycler=0.10.0=py27_0
  - cython=0.29.6=py27he6710b0_0
  - cytoolz=0.9.0.1=py27h14c3975_1
  - dask=1.1.4=py_0
  - dask-core=1.1.4=py_0
  - datashape=0.5.4=py27_1
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.2=py27_0
  - defusedxml=0.5.0=py27_1
  - distributed=1.26.0=py27_1
  - docutils=0.14=py27_0
  - entrypoints=0.3=py27_0
  - enum34=1.1.6=py27_1
  - et_xmlfile=1.0.1=py27_0
  - expat=2.2.6=he6710b0_0
  - fastcache=1.0.2=py27h14c3975_2
  - ffmpeg=4.0.2=ha0c5888_2
  - filelock=3.0.10=py27_0
  - flask=1.0.2=py27_1
  - flask-cors=3.0.7=py27_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - funcsigs=1.0.2=py27_0
  - functools32=3.2.3.2=py27_1
  - future=0.17.1=py27_0
  - futures=3.2.0=py27_0
  - get_terminal_size=1.0.0=haa9412d_0
  - gevent=1.4.0=py27h7b6447c_0
  - glib=2.56.2=hd408876_0
  - glob2=0.6=py27_1
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py27h10f8cd9_2
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.12=h23475e2_2
  - greenlet=0.4.15=py27h7b6447c_0
  - grin=1.2.1=py27_4
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py27h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - heapdict=1.0.0=py27_2
  - html5lib=1.0.1=py27_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py27_0
  - imageio=2.5.0=py27_0
  - imagesize=1.1.0=py27_0
  - importlib_metadata=0.8=py27_0
  - intel-openmp=2019.1=144
  - ipaddress=1.0.22=py27_0
  - ipykernel=4.10.0=py27_0
  - ipython=5.8.0=py27_0
  - ipython_genutils=0.2.0=py27_0
  - ipywidgets=7.4.2=py27_0
  - isort=4.3.15=py27_0
  - itsdangerous=1.1.0=py27_0
  - jbig=2.1=hdba287a_0
  - jdcal=1.4=py27_0
  - jedi=0.13.3=py27_0
  - jinja2=2.10=py27_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.1=py27_0
  - jupyter=1.0.0=py27_7
  - jupyter_client=5.2.4=py27_0
  - jupyter_console=5.2.0=py27_1
  - jupyter_core=4.4.0=py27_0
  - jupyterlab=0.33.11=py27_0
  - jupyterlab_launcher=0.11.2=py27h28b3542_0
  - keyring=18.0.0=py27_0
  - kiwisolver=1.0.1=py27hf484d3e_0
  - krb5=1.16.1=h173b8e3_7
  - lazy-object-proxy=1.3.1=py27h14c3975_2
  - libarchive=3.3.3=h5d8350f_5
  - libcurl=7.63.0=h20c2e04_1000
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblief=0.9.0=h7725739_1
  - libpng=1.6.35=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.0=h1ba5d50_4
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libtool=2.4.6=h7b6447c_5
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - libxslt=1.1.32=h1312cb7_0
  - linecache2=1.0.0=py27_0
  - llvmlite=0.27.0=py27hd408876_0
  - locket=0.2.0=py27_1
  - lxml=4.3.0=py27hefd8a0e_0
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - markupsafe=1.1.1=py27h7b6447c_0
  - matplotlib=2.2.3=py27hb69df0a_0
  - mccabe=0.6.1=py27_1
  - mistune=0.8.4=py27h7b6447c_0
  - mkl=2019.1=144
  - mkl-service=1.1.2=py27he904b0f_5
  - mkl_fft=1.0.10=py27ha843d7b_0
  - mkl_random=1.0.2=py27hd81dba3_0
  - more-itertools=5.0.0=py27_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.1=hdf1c602_3
  - mpmath=1.1.0=py27_0
  - msgpack-python=0.6.1=py27hfd86e86_1
  - multipledispatch=0.6.0=py27_0
  - navigator-updater=0.2.1=py27_0
  - nbconvert=5.4.1=py_2
  - nbformat=4.4.0=py27_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.3=0
  - networkx=2.2=py27_1
  - nltk=3.4=py27_1
  - nose=1.3.7=py27_2
  - notebook=5.7.6=py27_0
  - numba=0.42.0=py27h962f231_0
  - numexpr=2.6.9=py27h9e4a6bb_0
  - numpy=1.16.2=py27h7e9f1db_0
  - numpy-base=1.16.2=py27hde5b4d6_0
  - numpydoc=0.8.0=py27_0
  - odo=0.5.1=py27_0
  - olefile=0.46=py27_0
  - openh264=1.8.0=hdbcaa40_1000
  - openpyxl=2.6.1=py_0
  - openssl=1.1.1d=h7b6447c_2
  - packaging=19.0=py27_0
  - pandas=0.24.2=py27he6710b0_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py27_1
  - pango=1.42.4=h049681c_0
  - parso=0.3.4=py27_0
  - partd=0.3.9=py27_0
  - patchelf=0.9=he6710b0_3
  - path.py=11.5.0=py27_0
  - pathlib2=2.3.3=py27_0
  - patsy=0.5.1=py27_0
  - pcre=8.42=h439df22_0
  - pep8=1.7.1=py27_0
  - pexpect=4.6.0=py27_0
  - pickleshare=0.7.5=py27_0
  - pillow=5.4.1=py27h34e0f95_0
  - pip=19.2.3=py27_0
  - pixman=0.34.0=hceecf20_3
  - pkginfo=1.5.0.1=py27_0
  - pluggy=0.9.0=py27_0
  - ply=3.11=py27_0
  - prometheus_client=0.6.0=py27_0
  - prompt_toolkit=1.0.15=py27_0
  - psutil=5.6.1=py27h7b6447c_0
  - ptyprocess=0.6.0=py27_0
  - py=1.8.0=py27_0
  - py-lief=0.9.0=py27h7725739_1
  - pycairo=1.18.1=py27h2a1e443_0
  - pycodestyle=2.5.0=py27_0
  - pycosat=0.6.3=py27h14c3975_0
  - pycparser=2.19=py27_0
  - pycrypto=2.6.1=py27h14c3975_9
  - pycurl=7.43.0.2=py27h1ba5d50_0
  - pyflakes=2.1.1=py27_0
  - pygments=2.3.1=py27_0
  - pylint=1.9.2=py27_0
  - pyodbc=4.0.26=py27he6710b0_0
  - pyopenssl=19.0.0=py27_0
  - pyparsing=2.3.1=py27_0
  - pyqt=5.9.2=py27h05f1152_2
  - pyrsistent=0.14.11=py27h7b6447c_0
  - pysocks=1.6.8=py27_0
  - pytables=3.4.4=py27ha205bf6_0
  - pytest=4.3.0=py27_0
  - pytest-arraydiff=0.3=py27h39e3cac_0
  - pytest-astropy=0.5.0=py27_0
  - pytest-doctestplus=0.3.0=py27_0
  - pytest-openfiles=0.3.2=py27_0
  - pytest-remotedata=0.3.1=py27_0
  - python=2.7.15=h9bab390_6
  - python-dateutil=2.8.0=py27_0
  - python-libarchive-c=2.8=py27_6
  - python3-xlib=0.14=py27_0
  - pytz=2018.9=py27_0
  - pywavelets=1.0.2=py27hdd07704_0
  - pyyaml=3.13=py27h14c3975_0
  - pyzmq=17.1.2=py27h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=0.5.7=py_0
  - qtconsole=4.4.3=py27_0
  - qtpy=1.6.0=py_0
  - readline=7.0=h7b6447c_5
  - requests=2.21.0=py27_0
  - rope=0.12.0=py27_0
  - rospkg=1.0.38=py27_0
  - ruamel_yaml=0.15.46=py27h14c3975_0
  - scandir=1.10.0=py27h7b6447c_0
  - scikit-image=0.14.2=py27he6710b0_0
  - scikit-learn=0.20.3=py27hd81dba3_0
  - scipy=1.2.1=py27h7c811a0_0
  - seaborn=0.9.0=py27_0
  - send2trash=1.5.0=py27_0
  - setuptools=40.8.0=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27_0
  - sip=4.19.8=py27hf484d3e_0
  - six=1.12.0=py27_0
  - snappy=1.1.7=hbae5bb6_3
  - snowballstemmer=1.2.1=py27_0
  - sortedcollections=1.1.2=py27_0
  - sortedcontainers=2.1.0=py27_0
  - soupsieve=1.8=py27_0
  - sphinx=1.8.5=py27_0
  - sphinxcontrib=1.0=py27_1
  - sphinxcontrib-websupport=1.1.0=py27_1
  - spyder=3.3.3=py27_0
  - spyder-kernels=0.4.2=py27_0
  - sqlalchemy=1.3.1=py27h7b6447c_0
  - sqlite=3.26.0=h7b6447c_0
  - ssl_match_hostname=3.7.0.1=py27_0
  - statsmodels=0.9.0=py27h035aef0_0
  - subprocess32=3.5.3=py27h7b6447c_0
  - sympy=1.3=py27_0
  - tblib=1.3.2=py27_0
  - terminado=0.8.1=py27_1
  - testpath=0.4.2=py27_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py27_0
  - tornado=5.1.1=py27h7b6447c_0
  - tqdm=4.31.1=py_0
  - traceback2=1.4.0=py27_0
  - traitlets=4.3.2=py27_0
  - typing=3.6.6=py27_0
  - unicodecsv=0.14.1=py27_0
  - unittest2=1.1.0=py27_0
  - unixodbc=2.3.7=h14c3975_0
  - urllib3=1.24.1=py27_0
  - wcwidth=0.1.7=py27_0
  - webencodings=0.5.1=py27_1
  - werkzeug=0.14.1=py27_0
  - wheel=0.33.1=py27_0
  - widgetsnbextension=3.4.2=py27_0
  - wrapt=1.11.1=py27h7b6447c_0
  - wurlitzer=1.0.2=py27_0
  - x264=1!152.20180806=h14c3975_0
  - xlrd=1.2.0=py27_0
  - xlsxwriter=1.1.5=py27_0
  - xlwt=1.3.0=py27_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=hf484d3e_1
  - zict=0.1.4=py27_0
  - zipp=0.3.3=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch-gpu
  - torchvision
  - pip:
    - argparse==1.4.0
    - catkin-pkg==0.4.10
    - empy==3.3.4
    - secretstorage==2.3.1
    - tellopy
    - toml==0.10.0
prefix: /home/$USER/anaconda3

