ppo_params: {
  control_pub_name: '/racecar2/drive_parameters',
  ego_odom_name: '/racecar2/odom',
  lead_odom_name: '/racecar/odom',
  lidar_name: '/racecar2/scan',
  car_width: 0.5,
  scan_width: 270.0,
  lidar_range: 10.0,
  turn_clearance: 0.35,
  max_turn_angle: 34.0,
  min_speed: 0.5,
  max_speed: 4.0,
  min_dist: 0.1,
  max_dist: 3.0,
  no_obst_dist: 10.0,
  crash_threshold: 10,
  env: 'sim',
  rate: 10,
  load_path: './models/step_379800_model.pth',
  log_path: './',
  save_interval: 10,
  save_path: './models_2/',
  episode_length: 1200,
  gamma: 0.99,
  lam: 0.95,
  learning_rate: 2e-4,
  rl_clip_range: 0.1,
  total_steps: int(1e6),
  horizon_length: 1800,
  num_epochs: 4,
  minibatch_length: 1800,
  test_or_train: 'test',
}